rvm:
  - 1.9.3
  - 2.0.0
#  - jruby-19mode #Disabled for now

before_script:
  - psql -c 'create database postgres_ext_test;' -U postgres -h localhost
  - cp spec/dummy/config/database.yml.example spec/dummy/config/database.yml
  - RAILS_ENV=test rake db:migrate

notifications:
  email: 
    - git@danmcclain.net
addons:
  postgresql: '9.2'
